version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: yassineouhadi/jgen:cli
    # Other configuration options for the CLI service

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: yassineouhadi/jgen:web
    ports:
      - "3000:3000"
    # Other configuration options for the web service
