name: Extension Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install VS Code
      run: npm install -g vsce
      # You might need additional steps to install dependencies required by your extension

    - name: Install Dependencies
      run: npm install

    - name: Build Extension
      run: vsce package

    - name: Run Tests
      run: npm test
