name: Extension Tests

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false

    - name: Enter Directory
      run: cd server/Jgen
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn install
      
    - name: Run Tests
      run: yarn run test
