name: Extension Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn install

    - name: Generate Language Files
      run: yarn run langium:generate

    - name: Build Extension
      run: yarn run build

    - name: Run Tests
      run: yarn run test