name: Extension Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Enter Directory
      run: Jgen
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Generate Language Files
      run: npm run langium:generate

    - name: Build Extension
      run: npm run build

    - name: Run Tests
      run: npm run test
